### PR TITLE
Fix me forgetting to change the version when changing name of the pacakge.

### PR DESCRIPTION
**Pull request by BartoszKak0l**
F. Sorry I rushed and forgot to change the package version as well so it wasn't a complete fix :/

### CODE REVIEW

**Comment by BartoszKak0l** [comment]
Fixup to https://github.com/DougDougGithub/Babagaboosh/pull/33

**Comment by Kifrip** [comment]
You were faster than me, but you fricked up with the version apparently :O

**Comment by BartoszKak0l** [comment]
> You were faster than me, but you fricked up with the version apparently :O

Unfortunately yes. Maybe it would have been smart to spend more time double checking :D

**Comment by BartoszKak0l** [comment]
Merged in another PR

**Pull request closed without merging**
