### PR TITLE
Fixed requirements.txt AGAIN

### PR DESCRIPTION
**Pull request by Kifrip**
Currently when trying to run .\chatgpt_character.py
It throws the error below.
Adding azure-cognitiveservices-speech to requirements.txt fix it.

Traceback (most recent call last):
  File "C:\Users\anton\repos\Babagaboosh\chatgpt_character.py", line 4, in <module>
    from azure_speech_to_text import SpeechToTextManager
  File "C:\Users\anton\repos\Babagaboosh\azure_speech_to_text.py", line 2, in <module>
    import azure.cognitiveservices.speech as speechsdk
ModuleNotFoundError: No module named 'azure.cognitiveservices'

### CODE REVIEW

**Comment by Kifrip** [comment]
Well, I wasn't fast enough :(

**Comment by Kifrip** [comment]
The version that was merged was wrong. 
Please merge this PR to fix requirements.txt

Current code gives the error below:

pip install -r .\requirements.txt
ERROR: Could not find a version that satisfies the requirement azure-cognitiveservices-speech==12.19.0 (from versions: 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1b1, 1.26.0, 1.27.0, 1.28.0, 1.29.0, 1.30.0, 1.31.0, 1.32.1, 1.33.0, 1.34.0)
ERROR: No matching distribution found for azure-cognitiveservices-speech==12.19.0

**Comment by Kifrip** [comment]
Fix for https://github.com/DougDougGithub/Babagaboosh/pull/33

**Comment by BartoszKak0l** [comment]
btw. afaik blob is not needed but whatever :)

**Comment by Preloading** [comment]
merge is below

**Comment by Kifrip** [comment]
Ok, it is fixed now.

**Pull request closed without merging**
